- name: Deploy WAR file to Tomcat
  hosts: tomcat
  become: yes

  vars:
    tomcat_version: 9.0.113
    tomcat_install_dir: /opt/tomcat
    war_file: target/home/runner/work/simple-java-docker/simple-java-docker/java-webapp-1.0.0.war   # Adjust to your WAR file name

  tasks:
    - name: Copy WAR file to Tomcat webapps
      copy:
        src: "{{ war_file }}"
        dest: "{{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}/webapps/java-webapp.war"
        owner: tomcat
        group: tomcat
        mode: '0644'

    - name: Restart Tomcat
      systemd:
        name: tomcat
        state: restarted
